compare-bug-version-and-git-branch.sh

When groups are set in a bug, the bug is marked private and community members
will not be able to access it. This is wrong and should be marked as an error.

compare-bug-version-and-git-branch: bugs must be public

---

compare-bug-version-and-git-branch.sh

Currently compare-bug-version-and-git-branch smoke test does not check for the bug status. As a result it is very well possible that a patch/change submitted against a BZ under CLOSED status could bypass this test and proceed assuming success. This change will add an additional check for bug status. Please see the following link for more details on bug status life cycle:
http://gluster.readthedocs.org/en/latest/Contributors-Guide/Bug-report-Life-Cycle/
fixes gluster/release-tools#3
Signed-off-by: Anoop C S <anoopcs@redhat.com>

Add check for bug status in compare-bug-version-and-git-branch.sh 

---

centos-ci/README.md
centos-ci/libgfapi-python/gluster_libgfapi-python.xml
centos-ci/libgfapi-python/run-test.sh

Initial test for libgfapi-python. This runs the upstream libgfapi-python
functional test. The Jenkins job (gluster_libgfapi-python.xml) reserves
a machine, downloads and executes the run-test.sh script from GitHub.
URL: https://ci.centos.org/view/Gluster/job/gluster_libgfapi-python/

centos-ci: add libgfapi-python test-case

---

regression.sh

Allows us to run individual tests using the regression script instead of always running the full suite.

Allow regression.sh to accept lists of tests

---

centos-ci/libgfapi-python/gluster_libgfapi-python.xml
centos-ci/libgfapi-python/jenkins-job.py
centos-ci/libgfapi-python/run-test.sh

libgfapi-python was updated so that there are no changes needed to the
tox configuration and other files before running the tests.
This change also moves the resevation of the machine through Duffy from
the Jenkins job itself (the .xml file), into jenkins-job.py.

centos-ci/libgfapi-python: run all tests

---

centos-ci/README.md
centos-ci/nighly-builds/build.sh
centos-ci/nighly-builds/gluster_build-rpms.xml
centos-ci/nighly-builds/gluster_nightly-rpm-builds.xml
centos-ci/nighly-builds/jenkins-job.py

Build the HEAD of the master branch in mock agains epel-7-x86_64. Other
branches and CentOS versions/architectures can be selected with
environment variables.
The RPMs are published on http://artifacts.ci.centos.org/gluster/nightly
Other tests can monitor the repomd.xml file on the artifacts webserver
and use that as trigger to start testing. For each branch there is a
.repo file under http://artifacts.ci.centos.org/gluster/nightly/ . This
file can be used to install the nightly builds. On CentOS one would do
this:

centos-ci: add nightly build job

---

centos-ci/README.md
centos-ci/heketi-functional/gluster_heketi-functional.xml
centos-ci/heketi-functional/jenkins-job.py
centos-ci/heketi-functional/run-test.sh

There are some improvements that have been requested:
- https://github.com/heketi/heketi/issues/396
- https://github.com/heketi/heketi/pull/395
Once these changes have been made, the run-tests.sh script most likely
needs some small updates.
This job is already available in the CentOS CI:
https://ci.centos.org/view/Gluster/job/gluster_heketi-functional/

centis-ci: Add Jenkins job for Heketi functional tests

---

centos-ci/heketi-functional/jenkins-job.py

In case ghprbPullId is not set in the environment, Python returns None
with os.getenv(). This then translates to the string "None" and the
run-tests.sh script tries to use that as a pull-request number.
Assigning an empty sting in case the envionment variable is not set,
prevents any further issues.

centos-ci/heketi-functional: set ghprbPullId to empty string if unset

---

centos-ci/heketi-functional/run-test.sh

https://github.com/heketi/heketi/pull/400 replaces the use of glock with
godep. By checking the existance of GLOCKFILE, we can decide what tool
to "go get".

centos-ci/heketi-functional: use godep instead of glock

---

centos-ci/heketi-functional/gluster_heketi-functional.xml

Enabled a "post-build action":
> Set status for GitHub commit
> "Using GitHub status api sets status of the commit"
Reported-by: Luis Pabón <lpabon@redhat.com>
Tested-by: Luis Pabón <lpabon@redhat.com>
Tested-on: https://github.com/heketi/heketi/pull/420

centos-ci/heketi: report test result back to the GitHub pull request

---

centos-ci/gluster_strfmt/gluster_strfmt.xml
centos-ci/gluster_strfmt/jenkins-job.py
centos-ci/gluster_strfmt/run-test.sh

Kaleb is always watching out for these compile warnings (like a good
behaving package maintainer). Here the IRC log from the most recent
occurence, initiating the creation of this new Jenkins job.
16:08 < kkeithley> lots of *printf format string warnings creeping back in on 32-bit :-(
16:09 < kkeithley> particularly size_t and ssize_t that should use %z
16:09 < kkeithley> but don't
16:32 < ndevos> should we have a job for complaining about that?
16:33 < ndevos> we could even download and parse http://artifacts.ci.centos.org/gluster/nightly/master/6/i386/build.log every day
16:54 < kkeithley> +1 to having a job for 32-bit format string warnings
16:55 < ndevos> kkeithley: give me a regex that can be used to match such a build.log and I'll put it in the CentOS CI
16:56 < ndevos> kkeithley: …

centos-ci: add job to complain about string formatting warnings

---

centos-ci/gluster_strfmt/gluster_strfmt.xml

centos-ci/gluster_strfmt: only include warnings.txt once

---

centos-ci/nightly-builds/gluster_nightly-rpm-builds.xml

i386 was missing from the nightly builds. We actually want to do
verification of the build.log after the build with the gluster_strfmt
job. Without the builds, the job is pretty useless.

centos-ci/nightly-builds: build 32-bit packages too

---

centos-ci/gluster_strfmt/gluster_strfmt.xml

centos-ci/gluster_strfmt: add link to build log in the email

---

centos-ci/README.md
centos-ci/glusterfs-coreutils/gluster_coreutils.xml
centos-ci/glusterfs-coreutils/jenkins-job.py
centos-ci/glusterfs-coreutils/run-test.sh

After building nightly packages for CentOS-7/x86_64 from the master
branch in the GlusterFS repository, the glusterfs-coreutils need to be
tested against them.
Suggested-by: Anoop C S <anoopcs@redhat.com>

centos-ci: add test for glusterfs-coreutils

---

centos-ci/heketi-functional/run-test.sh

Currently, the patches are running from their root branch.  The patches need to run on the latest master.

Need to test on top of the latest master

---

build.sh

The two substantive changes are to turn off the BD translator and remove
-Werror (the BSD compilers are pickier than the Linux ones).  Also
removed the redirect to /dev/null because it's actually useful to see
the build results.
Signed-off-by: Jeff Darcy <jdarcy@redhat.com>

Fix FreeBSD builds

---

jenkins/scripts/centos-regression.sh
jenkins/scripts/netbsd7-regression.sh

We've got two blocks to skip regressions, which is essentially duplicating code. Let's merge them into one block.

Make the regression skip logic generic

---

regression.sh

The current one easily fails when used as a file name without escaping correctly.

Use the job ID for regression logs

---

centos-ci/nightly-builds/gluster_build-rpms.xml
centos-ci/nightly-builds/gluster_nightly-rpm-builds.xml

Packages are available for consumers by enabling the repository from
http://artifacts.ci.centos.org/gluster/nightly/release-3.9.repo

centos-ci: add release-3.9 to nightly builds

---

centos-ci/glusterd2/run-test.sh

`go get` supports mercurial, bazaar and subversion, along with git for
getting packages.
A new dependency for GD2 is served in a mercurial repo, which is
breaking the job.

cico/gd2: Install other SCM tools

---

smoke.sh

The gluster logs disappear on failed runs. We only have statedumps. That doesn't look right.

Don't clean up along in watchdog function

---

smoke.sh

Might possibly need this to get the `finish` function to trigger.

Kill gluster in watchdog so that EXIT is triggered

---

compare-bug-version-and-git-branch.sh

If the second line in the commit message is not empty, raise an error
It may be so that the title itself is long, but then it has to be on a single line
and should not be broken into mutliple lines with new-lines in between

check for empty line after subject line

---

compare-bug-version-and-git-branch.sh

If the bug is private, verify, then contact gluster-infra.
The admin part is removed because that's not specific
enough, and we should strive to do things in the open by
default.

Improve the error message

---

centos-ci/glusterd2/run-test.sh

The centos-ci job script for glusterd2 has been refactored. Now, the
script just clones the glusterd2 repo and then calls another script
within the clone. The actual environment setup and testing is performed
by the script in the clone.

centos-ci/glusterd2: Refactor job script

---

centos-ci/nightly-builds/build.sh

centos-ci/nightly-builds: capture build logs on the console

---

update-issue.py

Changed the parser code to detect issue references as made in rfc.sh (which is more lenient than the current version).
This was tested as presented in this gist: https://gist.github.com/ShyamsundarR/e012b975ccf5a9d80bffcce0d1b7bf2c
Basically a smaller version of this python code and a sample input file with valid and invalid inputs to test the parser.

Improve commit message parsing for finding issue reference

---

update-issue.py

Reworded comments against issues, to remove references to fixes or updates in the comment (a little more disambiguity), and to more generically refer to any patch that could be posted for the issue (like code, doc, etc. as such commits are also expected and are not necessarily fixes for the issue)

Reword comment on issues

---

compare-bug-version-and-git-branch.sh

So that our smokes can work on release branches (if they have used github id).

fix the issues with github issues backporting to release branch

---

centos-ci/jobs/build_rpms.yml
centos-ci/jobs/nightly-rpm-builds.yml

3.12 is the current release, and should generate nightly builds for testing.
3.11 and 3.8 are EOL, no further patches will be merged there. These
have been removed from the nightly builds.

centos-ci: do nightly builds for 3.12

---

centos-ci/scripts/nightly-builds.sh

Until now, adding the .repo file on the artifacts.ci.centos.org server
was done manually. Obviously this can be automated easily enough.
In the (near?) future, the nightly builds will get cleaned out after 30
days. This means that only recently modified contents will stay
available. The .repo files do not change normally, but with
automatically generating them, they are prevented from being garbage
collected.
URL: https://bugs.centos.org/view.php?id=13805 (delete old contents)

nightly-builds: generate a .repo file

---

update-issue.py

No longer need to check if a commit message is updated. That's an extra
API call. Might as well change that to one API call. Use
GERRIT_PATCHSET_NUMBER instead of GERRIT_PATCHSET_REVISION. The revision
is a hash and caused instant tracebacks.

Update the update-issue.py

---

centos-ci/heketi-functional/gluster_heketi-functional.xml

Luis Pabon is not maintaining Heketi anymore and transferred the
responsibilities to Michael Adam and Raghavendra Talur. The maintainers
are expected to be able to trigger the tests once a pull-request has
been sufficiently reviewd.

centos-ci/heketi: add rtalur as admin for triggering tests

---

centos-ci/nightly-vagrant/run-test.sh

Vagrant fails to start VMs on certain hypervisors. It seems that the
dependencies for the package are not correct and miss some bits.
Installing qemu-kvm-tools and qemu-img seems to resolve this.
The error that is logged when Vagrant fails to start a VM is like:
Call to virDomainCreateWithFlags failed: the CPU is incompatible with
host CPU: Host CPU does not provide required features: svm
The solution has been identified earlier for Heketi.
See-also: 5132671e ("add qemu-kvm to the list of needed bits")

nightly-vagrant: add missing dependencies for Vagrant

---

regression.sh

This has been broken ever since we moved to named threads. Fixes bug
1510735

Change how we guess the executable name for cores

---

centos-ci/jobs/gluster-kubernetes.yml
centos-ci/scripts/gluster-kubernetes.sh

A new Jenkins job in the CentOS CI has been added:
- https://ci.centos.org/view/Gluster/gluster_gluster-kubernetes
This job gets executed when an admin of the gluster-kubernetes
repository (admins are listed in the `jobs/gluster-kubernetes.yml`
file) leaves a comment in the GitHub Pull-Request with the following
phrases:
- ok to test
- test this please
(from https://github.com/jenkinsci/ghprb-plugin/blob/master/README.md)
Updates: gluster/gluster-kubernetes#23

centos-ci/gluster-kubernetes: add new test for pull-requests

---

centos-ci/heketi-functional/run-test.sh

According to research by Niels and KB, explicitly installing
sclo-vagrant1-vagrant seems to fix issues where libvirt
fails to bring up the vm with errors like:
Call to virDomainCreateWithFlags failed: the CPU is incompatible with host.
CPU: Host CPU does not provide required features: svm" (or vmx)

centos-ci/heketi: possible fix for problems with host-CPU

---

build.sh

It seems to break on FreeBSD for some reason, and since --enable-debug
already take care of "-g -O0", we can skip that.

Do not override CFLAGS

---

centos-ci/jobs/gluster-kubernetes.yml

The status updates were not showing in the Pull-Requests when tests got
started or after finishing. It seems that setting the status-context to
the "centos-ci" label makes this work correctly.
In addition to that, address the warning about the cronjob:
Spread load evenly by using ‘H/5 * * * *’ rather than ‘*/5 * * * *’
Updates: gluster/gluster-kubernetes#23

centos-ci/gluster-kubernetes: post test status updates a "centos-ci"

---

centos-ci/heketi-functional/run-test.sh

462f0d95ce38301a788fde8945d23631144a33dc
changed the directory from which to check for
the _sudo in tests/functional/lib.sh.
Hence the check failed.
This patch fixes this by using the proper relative
path (and using git grep instead of grep, for what
it's worth...).

centos-ci:heketi: fix regression introduced by last patch

---

centos-ci/heketi-functional/run-test.sh

The checks introduced to detect whether the target "test-functional"
exists was not working due to "set -e". Work around it in
a slightly awkward way. ;-)

centos-ci:heketi: fix failure to run tests due to "set -e"

---

centos-ci/heketi-functional/run-test.sh

scl apparently can't execute make directly.
Copy the echo-pipe-bash trick from the vagrant-nightly directory.

centos-ci:heketi: fix an error running make under scl

---

centos-ci/nightly-vagrant/run-test.sh

It seems vagrant boxes can no longer be downloaded from
"https://atlas.hashicorp.com" and all boxes should be downloaded from
"https://vagrantcloud.com". This change was done in
hashicorp/vagrant@5f955c3 .
See-also: sclorg-distgit/vagrant#3

centos-ci/nightly-vagrant: update the URL to download boxes from

---

centos-ci/jobs/gluster-kubernetes.yml
centos-ci/scripts/gluster-kubernetes.sh

This PR contains two changes that make the `gluster-kubernetes` job functional again and run it once every day.
This was suggested by @phlogistonjohn and @obnoxxx, but I can't add them as reviewers?

centos-ci/gluster-kubernetes: run the job once a day

---

centos-ci/heketi-functional/gluster_heketi-functional.xml

We currently only run the job on GitHub PullRequests. But we consume
components from other projects, so it is better to also run
periodically. Once a day should be sufficient, and we're nowhere near
the limit of resources we can consume.
By default the scripts already clone/checkout the master branch, with
the PR as option. No further changes to the scripts are needed atm.
Suggested-by: John Mulligan <jmulliga@redhat.com>

centos-ci/heketi-functional: run the job once a day

---

centos-ci/heketi-functional/gluster_heketi-functional.xml

It seems the list of admins that may trigger tests need to be separated
by spaces. The Jenkins webui gives the following message when commas are
used:
GitHub username may only contain alphanumeric characters or dashes and
cannot begin with a dash. Separate them with whitespaces.

centos-ci/heketi-functional: fix the notation of the admin list

---

distributed-tests/distributed-server.yml

This handler will copy the logs from '/var/log/glusterfs' of  connected servers to tester machine

Add a handler to run test server script task

---

glusterd2-test.sh

These tests are intended to be run as non-voting job (for now) against
glusterfs Gerrit changes. It has been verified that these tests pass on
a centos 7 machine.
This needs to be a non-voting job as we have one test (TestBitrot) that
fails spuriously. Once that is resolved, we can make this a voting job.
Signed-off-by: Prashanth Pai <ppai@redhat.com>

Add glusterd2 tests

---

github/commit.py
github/handle_bugzilla.py
github/handle_github.py
github/test_bugzilla.py
github/test_github.py

We don't use the parsed "Fixes/Updates" flag in the commit API yet. This will let us use it for changing status.

Add the ability to get bug/issue status from commit msg

---

github/handle_github.py
github/test_github.py

With this patch, if a github issue has label 'Type:Bug', then a patch posted on the same won't need any 'SpecApproved' and 'DocApproved' flags.
This allows us to come out of bugzilla completely, whenever we are ready.

github: handle even bug fixes through github

---

build.sh

bd translator got removed from code base through the following changes:
https://review.gluster.org/#/c/glusterfs/+/21812/
https://review.gluster.org/#/c/glusterfs/+/20702/
Signed-off-by: Anoop C S <anoopcs@redhat.com>

"--enable-bd-xlator" is no longer present in code base

---

github/commit.py

Handles the error like below:
```
Traceback (most recent call last):
File "/opt/qa/github/handle_github.py", line 187, in <module>
main(ARGS.repo, ARGS.dry_run, ARGS.comment_file)
File "/opt/qa/github/handle_github.py", line 165, in main
github.comment_on_issues(newissues, commit_msg)
File "/opt/qa/github/handle_github.py", line 47, in comment_on_issues
self._comment_on_issue(issue['id'], comment)
TypeError: string indices must be integers
```
This was not noticed before because we returned 'issues' as is, when patchset is 1.

github: handle error in commit message

---

compare-bug-version-and-git-branch.sh

So that, we don't close bugs against release branches by mistake.

Bugzilla: Compare against 'mainline' for 'master' patches

---

cleanup.sh

Clean /var/run/gluster, since there is a ton of socket here
(cleaned on reboot)
Do not try to kill glusterd twice
Remove /var/log/glusterfs/.cmd_log_history so we do not need to do
in others scripts
Remove /var/run/glusterd.socket so we can also remove that from others scripts

Do a cleaner cleanup

---

smoke.sh

When we merged new posix compliance test, we found out that the tests
were taking more than 200 seconds, and thus, the watchdog function killed
all processes, making the test fail. See https://github.com/gluster/glusterfs-patch-acceptance-tests/pull/199
for the details.

Increase the limit to 5 minutes

---

build.sh

https://github.com/gluster/glusterfs/pull/2060 fails on el-7 because
liburing-devel is not available on them. Hence adding this flag to our
build script so that the PR passes.
Note: 2060 is what introduces the 'disable-linux-io_uring' flag but we
can add it here even before it is merged because ./configure will
complain, but won't error out if an un-recognized (yet) option is given.
Signed-off-by: Ravishankar N <ravishankar@redhat.com>

add 'disable-linux-io_uring' flag for el-7 builds

---

regression.sh

Avoid that modified path-based variables end with ':'.
When this was done with 'LD_PRELOAD_PATH' variable, it caused that all
executables try to find its dynamic libraries in the current directory.
Fixes: #208
Signed-off-by: Xavi Hernandez <xhernandez@redhat.com>

Fix update of path-based environment variables
