compare-bug-version-and-git-branch.sh

compare-bug-version-and-git-branch: invert empty group check

---

regression.sh

regression.sh will now:
1. change the core pattern
2. dump the backtrace in case if there is any new corefile
3. reset the core pattern to defaults
Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

dump backtrace from corefile in console log

---

centos-ci/nightly-builds/gluster_build-rpms.xml
centos-ci/nightly-builds/gluster_nightly-rpm-builds.xml

centos-ci: add release-3.8 to nightly builds

---

centos-ci/heketi-functional/gluster_heketi-functional.xml
centos-ci/heketi-functional/jenkins-job.py
centos-ci/heketi-functional/run-test.sh

Fixes that @lpabon wants to see:
- install Docker
- configure to run on a GitHub pull-request

Centos ci/heketi functional

---

centos-ci/heketi-functional/run-test.sh

Need to move into heketi git directory before fetching change.

Make sure to move into git directory

---

centos-ci/README.md
centos-ci/nightly-vagrant/gluster_nightly-vagrant.xml
centos-ci/nightly-vagrant/gluster_run-tests-in-vagrant.xml
centos-ci/nightly-vagrant/jenkins-job.py
centos-ci/nightly-vagrant/run-test.sh

centos-ci: Add new glusterfs-nightly-vagrant Jenkins job

---

jenkins/jobs/add_misc_keys_to_root.xml
jenkins/jobs/add_to_salt.xml
jenkins/jobs/clang-build.xml
jenkins/jobs/compare-bug-version-and-git-branch.xml
jenkins/jobs/freebsd-smoke.xml
jenkins/jobs/gluster-swift-el7.xml
jenkins/jobs/glusterfs-devrpms-el6.xml
jenkins/jobs/glusterfs-devrpms-el7.xml
jenkins/jobs/glusterfs-devrpms.xml
jenkins/jobs/glusterfs-rpms-el6.xml
jenkins/jobs/glusterfs-rpms.xml
jenkins/jobs/libgfapi-python-pre-commit-el7.xml
jenkins/jobs/libgfapi-python-pre-commit-fedora.xml
jenkins/jobs/netbsd6-smoke.xml
jenkins/jobs/rackspace-netbsd7-regression-triggered.xml
jenkins/jobs/rackspace-regression-2GB-triggered.xml
jenkins/jobs/regression-test-burn-in.xml
jenkins/jobs/smoke.xml
jenkins/jobs/smoke_test_fedora.xml
jenkins/jobs/smoke_test_new_builders.xml
jenkins/jobs/swiftonfile-ci-el7.xml

Update the XML to the current state on the server.

Update all the xml.

---

jenkins/jobs/git.yml
jenkins/jobs/glusterfs-devrpms.yml
jenkins/jobs/glusterfs-rpms.yml
jenkins/jobs/properties.yml
jenkins/jobs/publishers.yml

The first yml file combining both the `glusterfs-rpms` job and `glusterfs-rpms-el7` jobs.

Convert rpm jobs into JJB yaml

---

jenkins/jobs/compare-bug-version-and-git-branch.yml
jenkins/jobs/git.yml

* Fixes bug 1354529. It needed choosing-strategy
* Makes sure the jobs look at every branch rather than just master.

Fix issues in JJB config

---

regression.sh

This should do two things:
* Create the folders that the regression tests need.
* Delete archives older than 15 days old.
Let me know if the time is too short.

Regression create and cleanup folders

---

centos-ci/glusterd2/gluster_glusterd2.xml
centos-ci/glusterd2/jenkins-job.py
centos-ci/glusterd2/run-test.sh

The job xml file will be added in the next commit.

centos-ci: Init job to build and test GlusterD2

---

.gitignore
requirements.txt
setup.py
tox.ini

Uses tox to test that the yaml files can be built.

Add the environment to test that jobs are correct

---

jenkins/jobs/smoke.yml
jenkins/scripts/smoke.sh

This time use `!include-raw:` rather than calling it from an external directory.

Convert smoke test to JJB

---

centos-ci/glusterd2/gluster_glusterd2.xml
centos-ci/heketi-functional/gluster_heketi-functional.xml

These jobs have now been fixed to report back correctly to Github.

Update heketi-functional and glusterd2 centos-ci jobs

---

jenkins/jobs/properties.yml

Use the throttle property: http://docs.openstack.org/infra/jenkins-job-builder/properties.html#properties.throttle
The plugin is already installed.

Add the ability to throttle jobs per node

---

regression.sh

Fix the error in the bash script

---

jenkins/jobs/compare-bug-version-and-git-branch.yml
jenkins/jobs/freebsd-smoke.yml
jenkins/jobs/glusterfs-devrpms.yml
jenkins/jobs/glusterfs-rpms.yml
jenkins/jobs/netbsd6-smoke.yml
jenkins/jobs/smoke.yml

Add timestamp wrappers and concurrent+throttle

---

smoke.sh

Remove the non-working archival bits.

Log dbench

---

.gitignore
centos-ci/jobs/gluster_glusto.yml
centos-ci/scripts/get-node-to-ansible.sh
centos-ci/scripts/glusto.sh
centos-ci/scripts/setup-glusto.yml
centos-ci/scripts/templates/gluster_tests_config.yml.j2

Glusto job for Centos CI

---

smoke.sh

Signed-off-by: Pranith Kumar K pkarampu@redhat.com

smoke: Add functionality to collect statedumps on hangs

---

build.sh

add --enable-gnfs option for configure, will be needed eventually and

---

update-issue.py

Changed the github repository against which identified issues in the commit message will reflect a comment linking back to the gerrit page.
Post all the changes, I think this is good to go live!

Lets take updating github issues from gerrit live!

---

centos-ci/heketi-functional/run-test.sh

centos-ci:heketi: install glide if needed

---

centos-ci/heketi-functional/run-test.sh

Needs to be checked from inside git checkout.

centos-ci:heketi: fix checks for glide et al

---

centos-ci/heketi-functional/run-test.sh

This can help in debugging issues.
Thanks to KB for the suggestion.

centos-ci:heketi: log virsh capabilites

---

centos-ci/heketi-functional/run-test.sh

this should being the 'hypervisor' feature missing from cap's

add qemu-kvm to the list of needed bits

---

update-issue.py

Currently if a new commit message is posted, the github issue
is updated with the same review URL. This is noisy.
This change, looks at the older commit message (if this is not
the first commit) and filters out issues referenced in the
older commit message, with the ones in the newer commit message
thereby reducing duplicate posts to the same github issue.
This is tested using the dry-run method only.
Signed-off-by: ShyamsundarR <srangana@redhat.com>

Add issue filtering by looking at the older commit message

---

smoke.sh

Smoke tests currently use 'replica 2' which we say we are discouraging. Need to have valid options used for smoke, so we have confidence in the volume type.
@ShyamsundarR @vbellur @nigelbabu @raghavendra-talur

add more valid test cases we support as part of smoke

---

centos-ci/jobs/nightly-rpm-builds.yml

centos-ci/nightly-builds: also build for release-3.13

---

centos-ci/heketi-functional/run-test.sh

no need any more to cd and manually run the script
Signed-off-by: Michael Adam <obnox@redhat.com>

centos-ci:heketi: we now have a test-functional target

---

centos-ci/heketi-functional/gluster_heketi-functional.xml

Signed-off-by: Michael Adam <obnox@redhat.com>

centos-ci:heketi: give more of the devs the right to trigger test runs

---

compare-bug-version-and-git-branch.sh

* Handle the new format for sending github id and bugzilla in
same format
* Allow MODIFIED as one of the valid status for accepting patch.
* If the bug is filed for a particular version, treat it as a
valid case for a patch in master branch.

bugzilla-check: bring multiple changes

---

build.sh

Thanks to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=881641

Remove the liblvm2app warning

---

distributed-tests/distributed-server.yml
distributed-tests/rackspace-server-manager.py

This commits includes the following:
- Add another functionality to check the availability of nodes
- Increase the timeout to 600 for waiting the server to restart

Add ping functionality to the code

---

distributed-tests/distributed-server.yml
distributed-tests/rackspace-server-manager.py

This commit includes:
- Add another function to check the SSH connections on the remote machines
- Increase the timeout of waiting for the server to restart

Add ssh_node function and increase timeout

---

distributed-tests/run-distributed-test.py

Add run-distributed-test.py file to run the distributed-test shell script with the server's IP on Jenkins builders

Add another script to run distributed-tests shell script 

---

distributed-tests/rackspace-server-manager.py
distributed-tests/run-distributed-test.py

distributed-test.sh sometime gets terminated because of failed connection from servers.
So adding more attempts to re run the script if it fails or get killed.

Change machine_name to node_name in delete_node function

---

distributed-tests/run-distributed-test.py

Exit the code with return value where code returns the number of failed tests on executing distributed-test.sh

Exit the code with return value 

---

distributed-tests/run-distributed-test.py

Add ArgParse in the script to get machine counts

---

distributed-tests/distributed-server.yml

Create the parent directory for storing the logs

---

distributed-tests/distributed-server.yml

Use delegate_to option to create directory first on localhost

---

compare-bug-version-and-git-branch.sh

and also output it to the screen, so the jobs also have the reasons for failure

check-bug: output the failure results to a file

---

compare-bug-version-and-git-branch.sh

Fix the regex to compare from the beginning of the line.
Otherwise, the logic was taking content from middle of the
line and also the content.

check-bug: fix the regex

---

github/handle_github.py

github: post full commit, instead of just title

---

distributed-tests/distributed-server.yml

Change the state to 'mounted' for /d xfs partition

---

glusterd2-test.sh

Run functional test using sudo

---

distributed-tests/create-vm.yml
distributed-tests/delete-vm.yml
distributed-tests/distributed-test-env
distributed-tests/distributed-test-runner.py
distributed-tests/distributed-test.sh
distributed-tests/run-distributed-test.py
distributed-tests/setup.yml

- create-vm.yml: Ansible playbook to create machines and inventory file
- delete-vm.yml: Ansible playbook to delete machines
- setup.yml: Playbook to do initial setups on machines including tasks
to compile and build glusterfs from master

This commit includes playbooks to manage instances on Rackspace:

---

distributed-tests/create-vm.yml
distributed-tests/distributed-test.sh
distributed-tests/setup.yml

Add task to authorize key on remote machines

---

distributed-tests/delete-vm.yml
distributed-tests/setup.yml

Change hosts to localhost when deleting machines

---

github/handle_bugzilla.py

handle_bugzilla: Handle a mistake in the script

---

github/handle_bugzilla.py
github/handle_github.py
github/test_bugzilla.py
github/test_github.py

This will add and update external tracker to bugzilla

Handle bugzilla external tracker

---

compare-bug-version-and-git-branch.sh

Add owner check for bug

---

github/handle_github.py

So we can upgrade the module without breakage and synchronisation

Make the code work with github 0.9.6 and 1.2.0

---

distributed-tests/setup.yml

build: remove 'bd-xlator' related references

---

github/handle_backport.py

- clone_bug function will do the cloning of given bug in relevant
branch with updates.
- gerrit_upgrade will deal with the cherry pick of a commit to
specified version
Signed-off-by: Deepshikha khandelwal <dkhandel@redhat.com>

Add a script to handle backport comment on Gerrit

---

distributed-tests/distributed-setup.yml

Signed-off-by: Deepshikha khandelwal <dkhandel@redhat.com>

Playbook to setup distributed environment for running distributed regression

---

tools/posix_compliance.sh

Signed-off-by: Amar Tumballi <amar@kadalu.io>

Just one posix-compliance test in smoke
